### ISSUE TITLE
Missing `>` from example component in the demo site.

### ISSUE THREAD

**Issue by nagyadam2092** [Metroxe/react-border-wrapper#1]
**Describe the bug**
Missing `>` from example component in the demo site.

**Props to Reproduce**
```jsx
<BorderWrapper
	// Props
>      // <-- that's missing from https://metroxe.github.io/react-border-wrapper/ on the bottom
	// Content
</BorderWrapper>
```

**Screenshots**
[https://imgur.com/a/C6oDkfc](https://imgur.com/a/C6oDkfc)

**Additional context (Optional)**
-

**Comment by Metroxe** [comment]
Thanks, I've pushed the fix

![image](https://user-images.githubusercontent.com/19210023/54969097-39ec5d80-4f3a-11e9-8db2-5123260b3fc2.png)
